Update tokenization.py
In function load_vocab(vocab_file) tf.gfile.Gfile throws an AttributeError: module 'tensorflow' has no attribute 'gfile'
I suppose in Tensorflow 2.0 and later versions the gfile has been moved to tf.io 

hence replaced tf.gfile.Gfile with tf.io.gfile.Gfile